/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainWindow.java
 *
 * Created on 23/03/2009, 22:41:51
 */

package NewGUI;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import NewGUI.GameBoard;
/**
 *
 * @author Roy
 */
public class MainWindow1 extends javax.swing.JFrame {


    // 0 = simple game
    // 1 = advance game
    private static int gameType = 0;
    // number of players
    private static int numOfPlayers = 1;
    private static String player1Name = "";
    private static String player2Name = "";
    private static String player3Name = "";
    private static String player4Name = "";

    // general return value parameter. will be used in file choosers
    private int returnVal = 0;

    public static int getGameType() {
        return gameType;
    }

    public static void setGameType(int gameType) {
        MainWindow1.gameType = gameType;
    }

    public static int getNumOfPlayers() {
        return numOfPlayers;
    }

    public static void setNumOfPlayers(int numOfPlayers) {
        MainWindow1.numOfPlayers = numOfPlayers;
    }

    public static String getPlayer1() {
        return player1Name;
    }

    public static void setPlayer1(String player1) {
        MainWindow1.player1Name = player1;
    }

    public static String getPlayer2() {
        return player2Name;
    }

    public static void setPlayer2(String player2) {
        MainWindow1.player2Name = player2;
    }

    public static String getPlayer3() {
        return player3Name;
    }

    public static void setPlayer3(String player3) {
        MainWindow1.player3Name = player3;
    }

    public static String getPlayer4() {
        return player4Name;
    }

    public static void setPlayer4(String player4) {
        MainWindow1.player4Name = player4;
    }

    public JLabel getScoreBoard() {
        return scoreBoard;
    }

    public static void setScoreBoardText(String text) {
        scoreBoard.setText(text);
    }

    /** Creates new form mainWindow */
    public MainWindow1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveGame = new javax.swing.JFileChooser();
        generalMessage = new javax.swing.JOptionPane();
        helpPage = new javax.swing.JDialog();
        okHelpButton = new javax.swing.JButton();
        helpText = new javax.swing.JLabel();
        bestResultsPageBasic = new javax.swing.JDialog();
        okBestBasicButton = new javax.swing.JButton();
        basicRecords = new javax.swing.JLabel();
        bestResultsPageAdvanced = new javax.swing.JDialog();
        okBestAdvancedButton = new javax.swing.JButton();
        advancedRecords = new javax.swing.JLabel();
        addWordToBoard = new javax.swing.JButton();
        currentPlayer = new javax.swing.JLabel();
        letterSack = new javax.swing.JLabel();
        scoreBoard = new javax.swing.JLabel();
        changeLetter = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        gameBoard1 = new NewGUI.GameBoard();
        playStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        loadMenuItem = new javax.swing.JMenuItem();
        gameMenuSeparator = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        bestResults = new javax.swing.JMenu();
        bestBasic = new javax.swing.JMenuItem();
        bestAdvanced = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        helpMenuItem1 = new javax.swing.JMenuItem();
        helpMenuSeparator1 = new javax.swing.JSeparator();
        aboutUsMenuItem1 = new javax.swing.JMenuItem();

        saveGame.setDialogTitle("Save a Game...");
        saveGame.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameActionPerformed(evt);
            }
        });

        generalMessage.setMessageType(2);

        helpPage.setMinimumSize(new java.awt.Dimension(645, 566));

        okHelpButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        okHelpButton.setText("Ok");
        okHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okHelpButtonActionPerformed(evt);
            }
        });

        helpText.setText("This is where the help text will be in the future...");

        javax.swing.GroupLayout helpPageLayout = new javax.swing.GroupLayout(helpPage.getContentPane());
        helpPage.getContentPane().setLayout(helpPageLayout);
        helpPageLayout.setHorizontalGroup(
            helpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPageLayout.createSequentialGroup()
                .addGroup(helpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpPageLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(helpText, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(helpPageLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(okHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        helpPageLayout.setVerticalGroup(
            helpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPageLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(helpText, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        bestResultsPageBasic.setMinimumSize(new java.awt.Dimension(645, 566));

        okBestBasicButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        okBestBasicButton.setText("Ok");
        okBestBasicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBestBasicButtonActionPerformed(evt);
            }
        });

        basicRecords.setText("here you will find the best results - basic");

        javax.swing.GroupLayout bestResultsPageBasicLayout = new javax.swing.GroupLayout(bestResultsPageBasic.getContentPane());
        bestResultsPageBasic.getContentPane().setLayout(bestResultsPageBasicLayout);
        bestResultsPageBasicLayout.setHorizontalGroup(
            bestResultsPageBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestResultsPageBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
            .addGroup(bestResultsPageBasicLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(okBestBasicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        bestResultsPageBasicLayout.setVerticalGroup(
            bestResultsPageBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestResultsPageBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(okBestBasicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bestResultsPageAdvanced.setMinimumSize(new java.awt.Dimension(645, 566));

        okBestAdvancedButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        okBestAdvancedButton.setText("Ok");
        okBestAdvancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBestAdvancedButtonActionPerformed(evt);
            }
        });

        advancedRecords.setText("here you will find the best results - advanced");

        javax.swing.GroupLayout bestResultsPageAdvancedLayout = new javax.swing.GroupLayout(bestResultsPageAdvanced.getContentPane());
        bestResultsPageAdvanced.getContentPane().setLayout(bestResultsPageAdvancedLayout);
        bestResultsPageAdvancedLayout.setHorizontalGroup(
            bestResultsPageAdvancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestResultsPageAdvancedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advancedRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
            .addGroup(bestResultsPageAdvancedLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(okBestAdvancedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        bestResultsPageAdvancedLayout.setVerticalGroup(
            bestResultsPageAdvancedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bestResultsPageAdvancedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advancedRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(okBestAdvancedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        addWordToBoard.setText("Add Word");
        addWordToBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordToBoardActionPerformed(evt);
            }
        });

        currentPlayer.setFont(new java.awt.Font("Tahoma", 1, 12));
        currentPlayer.setText("Now Playing: _______");

        letterSack.setIcon(new javax.swing.ImageIcon(getClass().getResource("letterSackThumb.jpg"))); // NOI18N
        letterSack.setText("Total Letters Left...");
        letterSack.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Letter Sack", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        scoreBoard.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score Board", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        changeLetter.setText("Change Letter");
        changeLetter.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                changeLetterComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                changeLetterComponentRemoved(evt);
            }
        });
        changeLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLetterActionPerformed(evt);
            }
        });

        doneButton.setText("Done!");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        playStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Play Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        gameMenu.setText("Game");
        gameMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameMenuKeyPressed(evt);
            }
        });

        newGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newGameMenuItem.setText("New Game");
        newGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuItemActionPerformed(evt);
            }
        });
        newGameMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newGameMenuItemKeyPressed(evt);
            }
        });
        gameMenu.add(newGameMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        saveMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMenuItemMouseClicked(evt);
            }
        });
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        saveMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveMenuItemKeyPressed(evt);
            }
        });
        gameMenu.add(saveMenuItem);

        loadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadMenuItem.setText("Load");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        loadMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loadMenuItemKeyPressed(evt);
            }
        });
        gameMenu.add(loadMenuItem);
        gameMenu.add(gameMenuSeparator);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        exitMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitMenuItemKeyPressed(evt);
            }
        });
        gameMenu.add(exitMenuItem);

        jMenuBar1.add(gameMenu);

        viewMenu.setText("View");
        jMenuBar1.add(viewMenu);

        bestResults.setText("Hall Of Fame");

        bestBasic.setText("Best Results - Basic Game");
        bestBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestBasicActionPerformed(evt);
            }
        });
        bestResults.add(bestBasic);

        bestAdvanced.setText("Best Results - Advanced Game");
        bestAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestAdvancedActionPerformed(evt);
            }
        });
        bestResults.add(bestAdvanced);

        jMenuBar1.add(bestResults);

        helpMenu1.setText("Help");

        helpMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        helpMenuItem1.setText("Help");
        helpMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuItem1ActionPerformed(evt);
            }
        });
        helpMenuItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                helpMenuItem1KeyPressed(evt);
            }
        });
        helpMenu1.add(helpMenuItem1);
        helpMenu1.add(helpMenuSeparator1);

        aboutUsMenuItem1.setText("About Us");
        helpMenu1.add(aboutUsMenuItem1);

        jMenuBar1.add(helpMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letterSack, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(changeLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(addWordToBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(playStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addWordToBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(currentPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(letterSack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMenuItemMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_saveMenuItemMouseClicked

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser loadFile = new JFileChooser();
        loadFile.showDialog(MainWindow1.this, "Load A Game...");
}//GEN-LAST:event_loadMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        returnVal = saveGame.showDialog(MainWindow1.this, "Save a Game");
}//GEN-LAST:event_saveMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       //method to exit
        scoreBoard.setText("Exit game from menu");
       dispose();

}//GEN-LAST:event_exitMenuItemActionPerformed

    /*
     * This is the event from extra button.
     * it currently pops up a default message that is configurable.
     */
    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        scoreBoard.setText("extra button");
        this.openGeneralMessage("Bitch Message", "Extra Button!");
}//GEN-LAST:event_doneButtonActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
        //Start a new game from menu.      
         NewGameDialog.startNewGame();
    }//GEN-LAST:event_newGameMenuItemActionPerformed

    private void gameMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameMenuKeyPressed

    private void newGameMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newGameMenuItemKeyPressed
         NewGameDialog.startNewGame();
    }//GEN-LAST:event_newGameMenuItemKeyPressed

    private void saveMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveMenuItemKeyPressed
        returnVal = saveGame.showDialog(MainWindow1.this, "Save a Game");
    }//GEN-LAST:event_saveMenuItemKeyPressed

    private void loadMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loadMenuItemKeyPressed
         JFileChooser loadFile = new JFileChooser();
        loadFile.showDialog(MainWindow1.this, "Load a Game...");
    }//GEN-LAST:event_loadMenuItemKeyPressed

    private void exitMenuItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitMenuItemKeyPressed
        //method to exit
        scoreBoard.setText("Exit game from key");
         dispose();
    }//GEN-LAST:event_exitMenuItemKeyPressed

    private void changeLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLetterActionPerformed
        //change letter button
        scoreBoard.setText("Change letter");
    }//GEN-LAST:event_changeLetterActionPerformed

    private void addWordToBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordToBoardActionPerformed
       //Add Word button
        scoreBoard.setText("Add Word");
    }//GEN-LAST:event_addWordToBoardActionPerformed

    private void helpMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuItem1ActionPerformed
        helpPage.setVisible(true);
}//GEN-LAST:event_helpMenuItem1ActionPerformed

    private void helpMenuItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_helpMenuItem1KeyPressed
        helpPage.setVisible(true);
}//GEN-LAST:event_helpMenuItem1KeyPressed

    private void changeLetterComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_changeLetterComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLetterComponentAdded

    private void changeLetterComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_changeLetterComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLetterComponentRemoved

    private void saveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameActionPerformed
    
        if (returnVal != saveGame.APPROVE_OPTION)
        {
            String fileName = saveGame.getSelectedFile().getName();
            scoreBoard.setText(fileName);
        }
    }//GEN-LAST:event_saveGameActionPerformed

    private void okHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okHelpButtonActionPerformed
        helpPage.dispose();
}//GEN-LAST:event_okHelpButtonActionPerformed

    private void okBestBasicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBestBasicButtonActionPerformed
        bestResultsPageBasic.dispose();
}//GEN-LAST:event_okBestBasicButtonActionPerformed

    private void okBestAdvancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBestAdvancedButtonActionPerformed
        bestResultsPageAdvanced.dispose();
}//GEN-LAST:event_okBestAdvancedButtonActionPerformed

    private void bestBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestBasicActionPerformed
        bestResultsPageBasic.setVisible(true);
    }//GEN-LAST:event_bestBasicActionPerformed

    private void bestAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestAdvancedActionPerformed
        bestResultsPageAdvanced.setVisible(true);
    }//GEN-LAST:event_bestAdvancedActionPerformed



    public static void initGameParamsToDefault()
    {
        gameType = 0;
        numOfPlayers = 1;
        player1Name = "";
        player2Name = "";
        player3Name = "";
        player4Name = "";
    }

    /*
     * This method is used to display a general message.
     * it can be used only inside MainWindow1
     */
    public void openGeneralMessage(String title, String text)
    {
//        generalMessage.setMessage(text);
       generalMessage.showMessageDialog(MainWindow1.this, text, title, 2);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow1().setVisible(true);
            }
        });
        return;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsMenuItem1;
    private javax.swing.JButton addWordToBoard;
    private javax.swing.JLabel advancedRecords;
    private javax.swing.JLabel basicRecords;
    private javax.swing.JMenuItem bestAdvanced;
    private javax.swing.JMenuItem bestBasic;
    private javax.swing.JMenu bestResults;
    private javax.swing.JDialog bestResultsPageAdvanced;
    private javax.swing.JDialog bestResultsPageBasic;
    private javax.swing.JButton changeLetter;
    private javax.swing.JLabel currentPlayer;
    private javax.swing.JButton doneButton;
    private javax.swing.JMenuItem exitMenuItem;
    private NewGUI.GameBoard gameBoard1;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JSeparator gameMenuSeparator;
    private javax.swing.JOptionPane generalMessage;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuItem helpMenuItem1;
    private javax.swing.JSeparator helpMenuSeparator1;
    private javax.swing.JDialog helpPage;
    private javax.swing.JLabel helpText;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel letterSack;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JButton okBestAdvancedButton;
    private javax.swing.JButton okBestBasicButton;
    private javax.swing.JButton okHelpButton;
    private static javax.swing.JLabel playStatus;
    private javax.swing.JFileChooser saveGame;
    private javax.swing.JMenuItem saveMenuItem;
    private static javax.swing.JLabel scoreBoard;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables



}
