/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayersNamesDialog.java
 *
 * Created on Mar 26, 2009, 1:07:14 AM
 */

package NewGUI;

/**
 *
 * @author Erez Reshef
 */
public class PlayersNamesDialog extends javax.swing.JDialog {


    
    public void initNames()
    {
        this.Player1TextField.setText(MainWindow1.getPlayer1());
        this.Player2TextField.setText(MainWindow1.getPlayer2());
        this.Player3TextField.setText(MainWindow1.getPlayer3());
        this.Player4TextField.setText(MainWindow1.getPlayer4());
    }

    public void setGameParameters(int numPlayers){       
        if (numPlayers == 2)
        {
            this.Player2Label.setEnabled(true);
            this.Player2TextField.setEnabled(true);
        }else
        {
            if(numPlayers == 3)
            {
                this.Player2Label.setEnabled(true);
                this.Player2TextField.setEnabled(true);
                this.Player3Label.setEnabled(true);
                this.Player3TextField.setEnabled(true);
            }
            else
            {
                if(numPlayers == 4)
                {
                    this.Player2Label.setEnabled(true);
                    this.Player2TextField.setEnabled(true);
                    this.Player3Label.setEnabled(true);
                    this.Player3TextField.setEnabled(true);
                    this.Player4Label.setEnabled(true);
                    this.Player4TextField.setEnabled(true);
                }

            }
        }

    }

    /** Creates new form PlayersNamesDialog */
    public PlayersNamesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        Player1Label = new javax.swing.JLabel();
        Player2Label = new javax.swing.JLabel();
        Player3Label = new javax.swing.JLabel();
        Player4Label = new javax.swing.JLabel();
        Player1TextField = new javax.swing.JTextField();
        Player2TextField = new javax.swing.JTextField();
        Player3TextField = new javax.swing.JTextField();
        Player4TextField = new javax.swing.JTextField();
        StartGameButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WelcomeLabel.setText("Select Player Names:");

        Player1Label.setText("Player 1:");

        Player2Label.setText("Player 2:");
        Player2Label.setEnabled(false);

        Player3Label.setText("Player 3:");
        Player3Label.setEnabled(false);

        Player4Label.setText("Player 4:");
        Player4Label.setEnabled(false);

        Player1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1TextFieldActionPerformed(evt);
            }
        });

        Player2TextField.setEnabled(false);

        Player3TextField.setEnabled(false);

        Player4TextField.setEnabled(false);

        StartGameButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartGameButton.setText("Start Game!");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackButton.setText("< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(WelcomeLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1Label)
                    .addComponent(Player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player2Label)
                    .addComponent(Player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player3Label)
                    .addComponent(Player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player4Label)
                    .addComponent(Player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1TextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Player1TextFieldActionPerformed

    /*
     * This methos will be used to start a new game.
     * all game params are global and located in MainWindow1.
     * */
    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        MainWindow1.setScoreBoardText("game type: " + MainWindow1.getGameType() + "\n" +
                "num of players: " + MainWindow1.getNumOfPlayers() + "\n" +
                "first plater name: " + MainWindow1.getPlayer1() );
       
        //dispose new game window at the end
        dispose();
}//GEN-LAST:event_StartGameButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        MainWindow1.setPlayer1(Player1TextField.getText());
        MainWindow1.setPlayer2(Player2TextField.getText());
        MainWindow1.setPlayer3(Player3TextField.getText());
        MainWindow1.setPlayer4(Player4TextField.getText());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewGameDialog nGDialog = new NewGameDialog(new javax.swing.JFrame(), true);
                nGDialog.setGameParameters();
                nGDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                 //dispose new game window at the end
                dispose();
                nGDialog.setLocation(100, 100);
                nGDialog.setVisible(true);
            }
        });
}//GEN-LAST:event_BackButtonActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        MainWindow1.initGameParamsToDefault();
        this.dispose();
}//GEN-LAST:event_CancelActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayersNamesDialog dialog = new PlayersNamesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Player1Label;
    private javax.swing.JTextField Player1TextField;
    private javax.swing.JLabel Player2Label;
    private javax.swing.JTextField Player2TextField;
    private javax.swing.JLabel Player3Label;
    private javax.swing.JTextField Player3TextField;
    private javax.swing.JLabel Player4Label;
    private javax.swing.JTextField Player4TextField;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables

}
