/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayersNamesDialog.java
 *
 * Created on Mar 26, 2009, 1:07:14 AM
 */

package NewGUI;

import scrabbleMain.Game;

/**
 *
 * @author Erez Reshef
 */
public class PlayersNamesDialog extends javax.swing.JDialog {

	private static String name1 = "";
	private static String name2 = "";
	private static String name3 = "";
	private static String name4 = "";
	
	
    public void initNames()
    {
        this.Player1TextField.setText(getName1());
        this.Player2TextField.setText(getName2());
        this.Player3TextField.setText(getName3());
        this.Player4TextField.setText(getName4());
    }

    public void setGameParameters(int numPlayers){       
        if (numPlayers == 2)
        {
            this.Player2Label.setEnabled(true);
            this.Player2TextField.setEnabled(true);
            PlayersNamesDialog.setName3("");
            PlayersNamesDialog.setName4("");
        }else
        {
            if(numPlayers == 3)
            {
                this.Player2Label.setEnabled(true);
                this.Player2TextField.setEnabled(true);
                this.Player3Label.setEnabled(true);
                this.Player3TextField.setEnabled(true);
                PlayersNamesDialog.setName4("");
            }
            else
            {
                if(numPlayers == 4)
                {
                    this.Player2Label.setEnabled(true);
                    this.Player2TextField.setEnabled(true);
                    this.Player3Label.setEnabled(true);
                    this.Player3TextField.setEnabled(true);
                    this.Player4Label.setEnabled(true);
                    this.Player4TextField.setEnabled(true);
                }
                else
                {
                    PlayersNamesDialog.setName2("");
                    PlayersNamesDialog.setName3("");
                    PlayersNamesDialog.setName4("");
                }

            }
        }

    }

    /** Creates new form PlayersNamesDialog */
    public PlayersNamesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        Player1Label = new javax.swing.JLabel();
        Player2Label = new javax.swing.JLabel();
        Player3Label = new javax.swing.JLabel();
        Player4Label = new javax.swing.JLabel();
        Player1TextField = new javax.swing.JTextField();
        Player2TextField = new javax.swing.JTextField();
        Player3TextField = new javax.swing.JTextField();
        Player4TextField = new javax.swing.JTextField();
        StartGameButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WelcomeLabel.setText("Select Player Names:");

        Player1Label.setText("Player 1:");

        Player2Label.setText("Player 2:");
        Player2Label.setEnabled(false);

        Player3Label.setText("Player 3:");
        Player3Label.setEnabled(false);

        Player4Label.setText("Player 4:");
        Player4Label.setEnabled(false);

        Player1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1TextFieldActionPerformed(evt);
            }
        });

        Player2TextField.setEnabled(false);

        Player3TextField.setEnabled(false);

        Player4TextField.setEnabled(false);

        StartGameButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StartGameButton.setText("Start Game!");
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BackButton.setText("< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Player4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Player4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(WelcomeLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1Label)
                    .addComponent(Player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player2Label)
                    .addComponent(Player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player3Label)
                    .addComponent(Player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player4Label)
                    .addComponent(Player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1TextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Player1TextFieldActionPerformed

    /*
     * This methos will be used to start a new game. get all game params from this method.
     * */
    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
    	//get all names:
    	setNamesActionPerformed();
    	//check if names are valid 
    	String message = checkIfValidNames();
    	if (!"".equals(message))
    	{
    		GeneralMessage.stratGeneralMessage(this, message, "Names feed problem");
    		return;
    	}
    	MainWindow = new MainWindow1();
        MainWindow.setVisible(true);

    	
    	
    	//this is where the game starts. here is an example of how to get all game params:
    	System.out.println("game type: " + NewGameDialog.getGameType());
    	System.out.println("num of players: " + NewGameDialog.getNumOfPlayers());
    	System.out.println("first player name: " + PlayersNamesDialog.getName1());
    	
    	//check if all names are valid
    	

        //dispose new game window at the end
        NewGameDialog.initGameParamsToDefault();
        initNamesToDefault();
        dispose();
}//GEN-LAST:event_StartGameButtonActionPerformed

    private static String checkIfValidNames()
    {
    	String message = "";
    	if (!checkIfValidName(name1))
    		message += "Please type a valid name for player1. \n";
    	if (NewGameDialog.getNumOfPlayers() > 1 && !checkIfValidName(name2))
    		message += "Please type a valid name for player2. \n";
    	if (NewGameDialog.getNumOfPlayers() > 2 && !checkIfValidName(name3))
    		message += "Please type a valid name for player3. \n";
    	if (NewGameDialog.getNumOfPlayers() > 3 && !checkIfValidName(name4))
    		message += "Please type a valid name for player4. \n";

    	return message;
    }
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
    	setNamesActionPerformed();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewGameDialog nGDialog = new NewGameDialog(new javax.swing.JFrame(), true);
                nGDialog.setGameParameters();
                nGDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                 //dispose new game window at the end
                dispose();
                nGDialog.setLocation(100, 100);
                nGDialog.setVisible(true);
            }
        });
}//GEN-LAST:event_BackButtonActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        initNamesToDefault();
        NewGameDialog.initGameParamsToDefault();
        this.dispose();
}//GEN-LAST:event_CancelActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayersNamesDialog dialog = new PlayersNamesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Player1Label;
    private javax.swing.JTextField Player1TextField;
    private javax.swing.JLabel Player2Label;
    private javax.swing.JTextField Player2TextField;
    private javax.swing.JLabel Player3Label;
    private javax.swing.JTextField Player3TextField;
    private javax.swing.JLabel Player4Label;
    private javax.swing.JTextField Player4TextField;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JLabel WelcomeLabel;
    public  MainWindow1 MainWindow;
    // End of variables declaration//GEN-END:variables


	public static String getName1() {
		return name1;
	}

	public static void setName1(String name1) {
		PlayersNamesDialog.name1 = name1;
	}

	public static String getName2() {
		return name2;
	}

	public static void setName2(String name2) {
		PlayersNamesDialog.name2 = name2;
	}

	public static String getName3() {
		return name3;
	}

	public static void setName3(String name3) {
		PlayersNamesDialog.name3 = name3;
	}

	public static String getName4() {
		return name4;
	}

	public static void setName4(String name4) {
		PlayersNamesDialog.name4 = name4;
	}
	
	public static void initNamesToDefault()
	{
		PlayersNamesDialog.setName1("");
		PlayersNamesDialog.setName2("");
		PlayersNamesDialog.setName3("");
		PlayersNamesDialog.setName4("");
	}
	
	public void setNamesActionPerformed()
	{
    	setName1(Player1TextField.getText());
    	setName2(Player2TextField.getText());
    	setName3(Player3TextField.getText());
    	setName4(Player4TextField.getText());
	}

	private static boolean checkIfValidName(String name) {
		if (name == null || "".equals(name) || name.startsWith(" "))
			return false;
		return true;
	}
}
