/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewGameDialog2.java
 *
 * Created on Mar 26, 2009, 12:44:26 AM
 */

package NewGUI;

/**
 *
 * @author Erez Reshef
 */
public class NewGameDialog extends javax.swing.JDialog {

    public void setGameParameters(){
        NumOfPlayersComboBox.setSelectedIndex(MainWindow1.getNumOfPlayers()-1);
        if (MainWindow1.getGameType() == 0)
        {
            AdvanceGameRadioButton.setSelected(false);
            SimpleGameRadioButton.setSelected(true);
        }
        else
        {
            AdvanceGameRadioButton.setSelected(true);
            SimpleGameRadioButton.setSelected(false);
        }
    }


    /** Creates new form NewGameDialog2 */
    public NewGameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        SelectNumOfPlayersLabel = new javax.swing.JLabel();
        SelectGameTypeLabel = new javax.swing.JLabel();
        NumOfPlayersComboBox = new javax.swing.JComboBox();
        AdvanceGameRadioButton = new javax.swing.JRadioButton();
        SimpleGameRadioButton = new javax.swing.JRadioButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Next.setFont(new java.awt.Font("Tahoma", 1, 14));
        Next.setText("Next >");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        WelcomeLabel.setText("Welcome to Scrabble!");

        SelectNumOfPlayersLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        SelectNumOfPlayersLabel.setText("Select Number Of Players:");

        SelectGameTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        SelectGameTypeLabel.setText("Select Game Type:");

        NumOfPlayersComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumOfPlayersComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"1 player", "2 Players", "3 Players", "4 Players" }));
        NumOfPlayersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfPlayersComboBoxActionPerformed(evt);
            }
        });

        AdvanceGameRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        AdvanceGameRadioButton.setText("Advance Game");
        AdvanceGameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvanceGameRadioButtonActionPerformed(evt);
            }
        });

        SimpleGameRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12));
        SimpleGameRadioButton.setSelected(true);
        SimpleGameRadioButton.setText("Simple Game");
        SimpleGameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleGameRadioButtonActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SelectNumOfPlayersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SelectGameTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumOfPlayersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(AdvanceGameRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SimpleGameRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(WelcomeLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectNumOfPlayersLabel)
                    .addComponent(NumOfPlayersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectGameTypeLabel)
                    .addComponent(SimpleGameRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdvanceGameRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdvanceGameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvanceGameRadioButtonActionPerformed
        // TODO add your handling code here:
        if (AdvanceGameRadioButton.isSelected())
            SimpleGameRadioButton.setSelected(false);
        MainWindow1.setGameType(1);
}//GEN-LAST:event_AdvanceGameRadioButtonActionPerformed

    private void SimpleGameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleGameRadioButtonActionPerformed
        // TODO add your handling code here:
        if (SimpleGameRadioButton.isSelected())
            AdvanceGameRadioButton.setSelected(false);
        MainWindow1.setGameType(0);
}//GEN-LAST:event_SimpleGameRadioButtonActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        MainWindow1.initGameParamsToDefault();
        //dispose new game window at the end
        this.dispose();
}//GEN-LAST:event_CancelActionPerformed

    private void NumOfPlayersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumOfPlayersComboBoxActionPerformed
        // TODO add your handling code here:
        MainWindow1.setNumOfPlayers(NumOfPlayersComboBox.getSelectedIndex() + 1);
    }//GEN-LAST:event_NumOfPlayersComboBoxActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlayersNamesDialog pNDialog = new PlayersNamesDialog(new javax.swing.JFrame(), true);
                pNDialog.setGameParameters(MainWindow1.getNumOfPlayers());
                pNDialog.initNames();
                pNDialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                 //dispose new game window at the end
                dispose();
                pNDialog.setLocation(100, 100);
                pNDialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_NextActionPerformed


    public static void startNewGame()
    {
        NewGameDialog nGDialog = new NewGameDialog(new javax.swing.JFrame(), true);
        nGDialog.setLocation(100, 100);
        nGDialog.setVisible(true);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewGameDialog dialog = new NewGameDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });                   
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdvanceGameRadioButton;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Next;
    private javax.swing.JComboBox NumOfPlayersComboBox;
    private javax.swing.JLabel SelectGameTypeLabel;
    private javax.swing.JLabel SelectNumOfPlayersLabel;
    private javax.swing.JRadioButton SimpleGameRadioButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables

}
